# Dockerfile.prod
# Use the official NGINX image
FROM nginx:alpine

# Copy the production HTML files into the default NGINX public directory
# COPY ./web /usr/share/nginx/html

# Expose port 80 (the default port NGINX listens on)
EXPOSE 80

HEALTHCHECK --interval=5s --timeout=3s --start-period=30s --retries=3 CMD wget -qO- http://localhost:80 || exit 1

# Start NGINX (this is the default behavior, no CMD or ENTRYPOINT needed)